openapi: 3.2.0
info:
  title: Visa BIN Attribute Sharing Service Full BIN List API
  description: Access a complete list of all of the Visa BINs and their associated BIN Attributes
  version: '1'
servers:
- url: https://sandbox.api.visa.com
  description: Sandbox server
security: []
tags:
- name: Full BIN List
  description: Access a complete list of all of the Visa BINs and their associated BIN Attributes
paths:
  /v2/binRangeDetails:
    post:
      tags:
      - Full BIN List
      summary: Bin Range Details Using POST V2
      description: The Full BIN List API provides access to Visa BIN Attributes such as Issuer BIN, Issuer Country, Issuer Billing Currency and Product Identifiers such as Product ID/name, Product Platform, Card type , Card Subtype
      operationId: Bin Range Details Using POST V2
      requestBody:
        description: Bin Range Details request payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinRangeDetailsRequestV2'
            examples:
              Default:
                summary: Default
                value:
                  requestHeader:
                    requestTS: '2024-01-01T23:10:41.000'
                    requestMessageID: test123
                  requestData:
                    binRangeSearchIndex: '0'
                    paymentAccountType: P
                    binRangeCount: '100'
        required: true
      responses:
        '200':
          description: BinRangeDetails Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BinRangeDetailsResponseV2'
              examples:
                Default:
                  summary: Default
                  value:
                    numRecordsReturned: '100'
                    areNextOffsetRecordsAvailable: Y
                    responseHeader:
                      responseMessageID: 34CACCTDTL2750820220617223228171
                    responseData:
                    - binRangeMaxNum: '401975999999999999999'
                      productID: B
                      binRangePaymentAccountType: P
                      accountRegionCode: '01'
                      accountCtryAlpha2Code: TL
                      posDomesticOnlyInd: N
                      comboCrdCd: A
                      accountFundingSourceSubtypeCd: N
                      multiAccountAccessInd: N
                      issuerBillingCurrCd: TPE
                      autoSubstntnInd: Y
                      issuerBin: '401975'
                      productIDName: Visa Infinite Privilege
                      commrclCrdLvl3EnhInd: N
                      accountFundingSourceCd: R
                      binLength: '6'
                      onlineGamblBlockInd: N
                      binRangeMinNum: '401975000000000000000'
                      commrclCrdLvl2Ind: N
                      platformCd: CN
                      accountBusName: A2B2 BANK
                      almInd: N
                      vauInd: Y
                      brandCd: VISA
                      sharedBinInd: N
                      regulatedBinCd: N
                    - binRangeMaxNum: '402201050999999999999'
                      productID: E
                      binRangePaymentAccountType: P
                      accountRegionCode: '04'
                      accountCtryAlpha2Code: US
                      posDomesticOnlyInd: N
                      comboCrdCd: C
                      accountFundingSourceSubtypeCd: ''
                      multiAccountAccessInd: N
                      issuerBillingCurrCd: USD
                      autoSubstntnInd: N
                      issuerBin: '402201'
                      productIDName: Visa Business
                      commrclCrdLvl3EnhInd: N
                      accountFundingSourceCd: D
                      binLength: '6'
                      onlineGamblBlockInd: N
                      binRangeMinNum: '402201050000000000000'
                      commrclCrdLvl2Ind: N
                      platformCd: BZ
                      accountBusName: ABD MARKETING
                      almInd: N
                      vauInd: N
                      brandCd: PROP
                      sharedBinInd: N
                      regulatedBinCd: N
                    - binRangeMaxNum: '414718009999999999999'
                      productID: S5
                      binRangePaymentAccountType: P
                      accountRegionCode: '05'
                      accountCtryAlpha2Code: PE
                      posDomesticOnlyInd: N
                      comboCrdCd: N
                      accountFundingSourceSubtypeCd: N
                      multiAccountAccessInd: S
                      issuerBillingCurrCd: PEN
                      autoSubstntnInd: N
                      issuerBin: '41471800'
                      productIDName: Visa Signature
                      commrclCrdLvl3EnhInd: N
                      accountFundingSourceCd: R
                      binLength: '8'
                      onlineGamblBlockInd: N
                      binRangeMinNum: '414718000000000000000'
                      commrclCrdLvl2Ind: N
                      platformCd: CO
                      accountBusName: ABD BANK, NATIONAL ASSOCIATION
                      almInd: N
                      vauInd: N
                      brandCd: VISA
                      sharedBinInd: N
                      regulatedBinCd: N
                    responseStatus:
                      statusDescription: Success
                      statusCode: CDI000
                    totalRecordsCount: '8203810'
        '400':
          description: Request Data Invalid
          content: {}
        '401':
          description: Unauthorized
          content: {}
        '500':
          description: Error Codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorCodes-3'
      x-operationVersions:
      - label: v1
        operationPointer: '#/paths/~1v1~1binRangeDetails/post'
        default: false
      - label: v2 - Latest
        operationPointer: '#/paths/~1v2~1binRangeDetails/post'
        default: false
      x-codegen-request-body-name: Bin Range Details Request
      x-hideTryIt: true
  /v1/binRangeDetails:
    post:
      tags:
      - Full BIN List
      summary: Bin Range Details Using POST
      description: Full Bin List
      operationId: Bin Range Details Using POST V1
      requestBody:
        description: Bin Range Details request payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinRangeDetailsRequestV1-1'
            examples:
              Default:
                summary: Default
                value:
                  requestHeader:
                    requestTS: '2024-02-01T23:10:41.000'
                    requestMessageID: test123
                  requestData:
                    binRangeSearchIndex: '0'
                    binRangeCount: '100'
        required: true
      responses:
        '200':
          description: BinRangeDetails Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BinRangeDetailsResponseV1-1'
              examples:
                Default:
                  summary: Default
                  value:
                    numRecordsReturned: '100'
                    areNextOffsetRecordsAvailable: Y
                    responseHeader:
                      responseMessageID: 34CACCTDTL2750820220617223228171
                    responseData:
                    - binRangeMaxNum: '401975999999999999999'
                      accountFundingSourceCd: R
                      productID: B
                      binRangePaymentAccountType: P
                      accountRegionCode: '01'
                      accountCtryAlpha2Code: TL
                      binRangeMinNum: '401975000000000000000'
                      accountFundingSourceSubtypeCd: N
                      platformCd: CN
                      accountBusName: A2B2 BANK
                      issuerBillingCurrCd: TPE
                      issuerBin: '401975'
                      productIDName: Visa Infinite Privilege
                    - binRangeMaxNum: '402201050999999999999'
                      accountFundingSourceCd: D
                      productID: E
                      binRangePaymentAccountType: P
                      accountRegionCode: '04'
                      accountCtryAlpha2Code: US
                      binRangeMinNum: '402201050000000000000'
                      accountFundingSourceSubtypeCd: ''
                      platformCd: BZ
                      accountBusName: ABD MARKETING
                      issuerBillingCurrCd: USD
                      issuerBin: '402201'
                      productIDName: Visa Business
                    - binRangeMaxNum: '414718009999999999999'
                      accountFundingSourceCd: R
                      productID: S5
                      binRangePaymentAccountType: P
                      accountRegionCode: '05'
                      accountCtryAlpha2Code: PE
                      binRangeMinNum: '414718000000000000000'
                      accountFundingSourceSubtypeCd: N
                      platformCd: CO
                      accountBusName: ABD BANK, NATIONAL ASSOCIATION
                      issuerBillingCurrCd: PEN
                      issuerBin: '41471800'
                      productIDName: Visa Signature
                    responseStatus:
                      statusDescription: Success
                      statusCode: CDI000
                    totalRecordsCount: '8203810'
        '300':
          description: Requesting Client IP is invalid
          content: {}
        '400':
          description: Request Data Invalid
          content: {}
        '401':
          description: Unauthorized
          content: {}
        '500':
          description: Error Codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorCodes-3'
      x-codegen-request-body-name: Bin Range Details Request
components:
  schemas:
    requestDataV2:
      title: requestDataV2
      required:
      - binRangeCount
      - binRangeSearchIndex
      type: object
      properties:
        binRangeCount:
          minLength: 1
          type: string
          description: Number of records being requested (maximum number of records to be displayed)
        paymentAccountType:
          maxLength: 1
          minLength: 0
          type: string
          description: Identifier for whether account is a PAN ('P') or Token ('T')
        binRangeSearchIndex:
          minLength: 1
          type: string
          description: Starting index - to be used for paginating through the records. Starting possible values are 0, 100, 200, &,500 (multiples of hundred)
    requestDataV1-1:
      title: requestDataV1
      required:
      - binRangeCount
      - binRangeSearchIndex
      type: object
      properties:
        binRangeCount:
          type: string
          description: Number of records being requested(maximum number of records to be displayed)
        binRangeSearchIndex:
          type: string
          description: Starting index - to be used for paginating through the records. Starting possible values are 0, 100, 200, &, 500(multiples of hundred)
    responseStatus-3:
      title: responseStatus
      type: object
      properties:
        statusCode:
          maxLength: 6
          minLength: 6
          type: string
          description: Status Code of the Service Request
        statusDescription:
          maxLength: 250
          minLength: 10
          type: string
          description: A description of the StatusCode. A brief description indicating the result of the Service Request
    responseDataV2-2:
      title: responseData
      required:
      - binRangeMaxNum
      - binRangeMinNum
      - binRangePaymentAccountType
      type: object
      properties:
        almInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicates if BIN or Account Range participate in Account Level Management
        vauInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Visa Account Updater enabled indicator
        brandCd:
          maxLength: 4
          minLength: 0
          type: string
          description: Identifies if the brand or brands is associated with the account range.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section8">Brand Indicator</a>
        binLength:
          maxLength: 2
          minLength: 0
          type: string
          description: Provides BIN length - 6 or 8 digits
        issuerBin:
          maxLength: 8
          minLength: 0
          type: string
          description: Issuer BIN of requested PAN/TOKEN
        productID:
          maxLength: 2
          minLength: 0
          type: string
          description: An identifier associated with a unique card product - combination of card brand, platform, class and scheme equates to a unique product ID.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section0">Product ID</a>
        comboCrdCd:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicator for combo card <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section6">Combo Card Indicator</a>
        platformCd:
          maxLength: 2
          minLength: 0
          type: string
          description: The code of product platform, e.g. Business, Consumer, Commercial, Government.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section3">Product Platform Code</a>
        sharedBinInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Set to true if BIN shared by multiple issuers
        productIDName:
          maxLength: 50
          minLength: 0
          type: string
          description: The name associated with the product ID, e.g. Visa Traditional, Visa Signature, Visa Government Purchasing, etc.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section0">Product Name</a>
        accountBusName:
          maxLength: 240
          minLength: 0
          type: string
          description: Issuer Name
        binRangeMaxNum:
          maxLength: 21
          minLength: 0
          type: string
          description: maximum number of BIN range
        binRangeMinNum:
          maxLength: 21
          minLength: 0
          type: string
          description: minimum number of BIN range
        regulatedBinCd:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicator for regulated BINs <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section7">Regulated BINs Indicator</a>
        autoSubstntnInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Auto Substantiation enabled indicator
        accountRegionCode:
          maxLength: 2
          minLength: 0
          type: string
          description: Issuer Region <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section9">Issuer Region</a>
        commrclCrdLvl2Ind:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicates if transaction qualifies for Level 2 interchange rates
        posDomesticOnlyInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Domestic Only BIN or Account Ranges
        issuerBillingCurrCd:
          maxLength: 3
          minLength: 0
          type: string
          description: Issuer Billing Currency Code <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section5">Currency Code</a>
        onlineGamblBlockInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicates whether Online Gambling permitted or not
        commrclCrdLvl3EnhInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Indicates if transaction qualifies for Level 3 interchange rates
        accountCtryAlpha2Code:
          maxLength: 2
          minLength: 0
          type: string
          description: Country Code Alpha Code <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section4">Country Code</a>
        multiAccountAccessInd:
          maxLength: 1
          minLength: 0
          type: string
          description: Multi Account Access indicator <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section10">Multi Account Access Indicator</a>
        accountFundingSourceCd:
          maxLength: 1
          minLength: 0
          type: string
          description: The code of account funding source for the card, e.g. Credit, Debit, Prepaid, Charge, Deferred Debit.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section1">Account Funding Source</a>
        binRangePaymentAccountType:
          maxLength: 1
          minLength: 0
          type: string
          description: The type of account - value can either 'P' for PAN or 'T' for TOKEN
        accountFundingSourceSubtypeCd:
          maxLength: 1
          minLength: 0
          type: string
          description: The code for account funding source subtype, such as reloadable and non-reloadable.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#section2">Account Funding Source Subtype</a>
    responseHeader-2:
      title: responseHeader
      type: object
      properties:
        responseMessageId:
          maxLength: 33
          minLength: 33
          type: string
          description: A combination of Service Id, Application Id, an Integer and current Timestamp that uniquely identifies the current request-response processing
    responseHeader-3:
      title: responseHeader
      type: object
      properties:
        responseMessageId:
          type: string
          description: A combination of Service Id, Application Id, an Integer and current Timestamp that uniquely identifies the current request-response processing
    requestHeader-4:
      title: requestHeader
      required:
      - requestMessageID
      - requestTS
      type: object
      properties:
        requestTS:
          maxLength: 23
          type: string
          description: 'Date and time at which Request is sent (up to milliseconds in GMT). Ex: 2008-09-19T00:00:00.000'
          format: YYYY-MM-DDThh:mm:ss.sss
        requestMessageID:
          maxLength: 50
          type: string
          description: A string which uniquely identifies the service request. Requesting application need to create this unique message Id
    BinRangeDetailsResponseV1-1:
      title: BinRangeDetailsResponse
      required:
      - areNextOffsetRecordsAvailable
      - numRecordsReturned
      - totalRecordsCount
      type: object
      properties:
        responseData:
          $ref: '#/components/schemas/responseDataV1-3'
        responseHeader:
          $ref: '#/components/schemas/responseHeader-3'
        responseStatus:
          $ref: '#/components/schemas/responseStatus-4'
        totalRecordsCount:
          type: string
          description: total number of records present
        numRecordsReturned:
          type: string
          description: number of records returned
        areNextOffsetRecordsAvailable:
          type: string
          description: more records available?
    requestHeader-3:
      title: requestHeader
      required:
      - requestMessageID
      - requestTS
      type: object
      properties:
        requestTS:
          maxLength: 23
          minLength: 0
          type: string
          description: 'Date and time at which Request is sent (up to milliseconds in GMT). Ex: 2024-02-19T00:00:00.000'
          format: YYYY-MM-DDThh:mm:ss.sss
        requestMessageID:
          maxLength: 50
          minLength: 0
          type: string
          description: A string which uniquely identifies the service request. Requesting application need to create this unique message Id
    BinRangeDetailsRequestV2:
      title: BinRangeDetailsRequest
      type: object
      properties:
        requestData:
          $ref: '#/components/schemas/requestDataV2'
        requestHeader:
          $ref: '#/components/schemas/requestHeader-3'
    BinRangeDetailsResponseV2:
      title: BinRangeDetailsResponse
      required:
      - areNextOffsetRecordsAvailable
      - numRecordsReturned
      - totalRecordsCount
      type: object
      properties:
        responseData:
          $ref: '#/components/schemas/responseDataV2-2'
        responseHeader:
          $ref: '#/components/schemas/responseHeader-2'
        responseStatus:
          $ref: '#/components/schemas/responseStatus-3'
        totalRecordsCount:
          minLength: 1
          type: string
          description: total number of records present
        numRecordsReturned:
          minLength: 1
          type: string
          description: number of records returned
        areNextOffsetRecordsAvailable:
          maxLength: 1
          minLength: 1
          type: string
          description: more records available?
    responseDataV1-3:
      title: responseData
      required:
      - binRangeMaxNum
      - binRangeMinNum
      - binRangePaymentAccountType
      type: object
      properties:
        issuerBin:
          type: string
          description: Issuer Bin of requested PAN/TOKEN
        productID:
          type: string
          description: An identifier associated with a unique card product - combination of card brand, platform, class and scheme equates to a unique product ID.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#productid">Product ID</a>
        platformCd:
          type: string
          description: The code of product platform, e.g. Business, Consumer, Commercial, Government.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#platformcode">Product Platform Code</a>
        productIDName:
          type: string
          description: The name associated with the product ID, e.g. Visa Traditional, Visa Signature, Visa Government Purchasing, etc.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#productid">Product Name</a>
        accountBusName:
          type: string
          description: Issuer Name
        binRangeMaxNum:
          type: string
          description: maximum number of bin range
        binRangeMinNum:
          type: string
          description: minimum number of bin range
        accountRegionCode:
          type: string
          description: Issuer Region
        issuerBillingCurrCd:
          type: string
          description: Issuer Billing Currency Code <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#currencycode">Currency Code</a>
        accountCtryAlpha2Code:
          type: string
          description: Country Code Alpha Code <br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#countrycode">Country Code</a>
        accountFundingSourceCd:
          type: string
          description: The code of account funding source for the card, e.g. Credit, Debit, Prepaid, Charge, Deferred Debit.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#accountfundingsource">Account Funding Source</a>
        binRangePaymentAccountType:
          type: string
          description: The type of account - value can either 'P' for PAN or 'T' for TOKEN
        accountFundingSourceSubtypeCd:
          type: string
          description: The code for account funding source subtype, such as reloadable and non-reloadable.<br>Refer to <a href="/capabilities/visa-bin-attribute-sharing-service/docs-request-response-codes#accountfundingsourcesubtype">Account Funding Source Subtype</a>
    BinRangeDetailsRequestV1-1:
      title: BinRangeDetailsRequest
      type: object
      properties:
        requestData:
          $ref: '#/components/schemas/requestDataV1-1'
        requestHeader:
          $ref: '#/components/schemas/requestHeader-4'
    responseStatus-4:
      title: responseStatus
      type: object
      properties:
        statusCode:
          type: string
          description: Status Code of the Service Request
        statusDescription:
          type: string
          description: A description of the StatusCode. A brief description indicating the result of the Service Request
    errorCodes-3:
      title: errorCodes
      type: object
      properties:
        CDI001:
          type: object
          description: Internal service failure
        CDI002:
          type: object
          description: XML Parsing Failure
        CDI012:
          type: object
          description: Request header length is invalid
        CDI052:
          type: object
          description: Client Authentication failed
        CDI071:
          type: object
          description: Exception in Group level entitlement process
        CDI246:
          type: object
          description: Bin Range Search Index validation failure
        CDI247:
          type: object
          description: Bin Range Count validation failure
        CDI249:
          type: object
          description: Payment Account Type validation failure
        CDI250:
          type: object
          description: Atleast one of the required/mandatory fields is missing in the request
x-tagGroups:
- name: API Reference
  tags:
  - BIN File Transfer
  - BIN Files Metadata
  - Full BIN List
  - Issuer API
  - Single BIN Lookup
